import React from 'react';
import { Link, usePage } from '@inertiajs/react';
import LegalLayout from '../../Layouts/LegalLayout';

export default function Cookies({ company, is_authenticated, cookie_details }) {
    const { navigation } = usePage().props;
    const sessionDuration = cookie_details.expire_on_close ? 'Until the browser session ends' : `${cookie_details.lifetime_minutes} minutes of inactivity`;
    const sections = [
        { id: 'what-cookies-are', title: 'Small files, specific jobs', content: <><p>Cookies are small values saved by your browser and sent with later requests to a website. They help a service recognise a session and protect actions such as saving progress or submitting a supply order.</p><p>This policy explains the cookies used by the current Zombie Base Defender application. For information about server-side profile and game records, read the <Link href={navigation.privacy}>Privacy Policy</Link>.</p></> },
        { id: 'cookie-inventory', title: 'Cookies used by this site', content: <><p>The current application uses first-party cookies for session continuity and request security. The configured session duration is shown below.</p><div className="legal-table-wrap"><table><caption>Essential cookie inventory</caption><thead><tr><th scope="col">Cookie</th><th scope="col">Purpose</th><th scope="col">Duration</th></tr></thead><tbody><tr><th scope="row"><code>{cookie_details.session_name}</code><small>ESSENTIAL · FIRST PARTY</small></th><td>Recognises your browser session so the Service can maintain access and process requests.</td><td>{sessionDuration}</td></tr><tr><th scope="row"><code>XSRF-TOKEN</code><small>ESSENTIAL · FIRST PARTY</small></th><td>Helps protect state-changing requests from cross-site request forgery.</td><td>{cookie_details.lifetime_minutes} minutes; renewed with activity</td></tr></tbody></table></div><p>These cookies do not contain your complete game inventory. Progress and virtual-item records are stored by the Service. Browser settings and session restoration can affect when locally stored cookies are removed.</p></> },
        { id: 'optional-cookies', title: 'Analytics & advertising', content: <><div className="legal-callout"><strong>No optional tracking is configured in this build.</strong><p>The application currently includes no analytics or advertising-cookie integration, so there are no optional tracking categories to switch on here.</p></div><p>If optional cookies are introduced, this policy and the relevant controls must be updated. Where consent is required, those cookies must not be set before your choice, and withdrawing consent must be as easy as giving it.</p></> },
        { id: 'other-technologies', title: 'Other browser technologies', content: <><p>The current game’s sound setting is held in memory while the application is running. It is not saved as a persistent audio-preference cookie or local-storage entry.</p><p>Fonts are loaded from Bunny Fonts. Your browser makes a network request to that provider, which receives the information required to serve the resource. This is a separate consideration from the first-party session cookies listed above.</p></> },
        { id: 'browser-controls', title: 'Your browser, your controls', content: <><p>You can inspect, delete or block cookies through your browser’s privacy or site-data settings. Look for this website in its list of stored site data. Private-browsing modes may remove cookies when the private session ends.</p><ul><li>Deleting a session cookie can sign you out or disconnect the browser from the current profile.</li><li>Blocking security cookies can cause progress updates or supply requests to fail.</li><li>Clearing browser data does not itself erase server-side game or order records.</li></ul><p>To ask about deletion of server-side information, contact the operator using the details below. Your browser’s own help centre explains the controls for your browser version.</p></> },
        { id: 'cookie-updates', title: 'Keeping this policy current', content: <><p>Cookie names and lifetimes can change with the service configuration. The inventory above reflects the application’s current session settings. New integrations should be assessed and documented before they are enabled.</p><p>The revision date at the top identifies the latest update to this document.</p></> },
    ];
    return <LegalLayout type="cookies" title="Cookie Policy" introduction="A little memory keeps your session together. Here’s what your browser stores, why it matters and how you stay in control." company={company} authenticated={is_authenticated} sections={sections} summary={['Session cookies keep your browser connected.', 'A security cookie helps protect your requests.', 'No optional tracking is configured in this build.', 'Clearing cookies does not erase server-side progress.']} />;
}
