import React from 'react';
import { Link, usePage } from '@inertiajs/react';
import LegalLayout from '../../Layouts/LegalLayout';

export default function Privacy({ company, is_authenticated }) {
    const { navigation } = usePage().props;
    const sections = [
        { id: 'responsibility', title: 'Who is responsible', content: <><p>{company?.name || 'The operator listed below'} operates Zombie Base Defender and is responsible for the personal information processed through this Service. The company’s registration, address and contact details are provided at the end of this notice.</p><p>This notice covers the game and this website. Independently operated sites have their own privacy practices.</p></> },
        { id: 'information', title: 'Information the game uses', content: <><p>The Service processes information needed to maintain the game and your access:</p><ul><li><strong>Profile information:</strong> a player identifier, display name and any account details associated with your access.</li><li><strong>Game progress:</strong> wave progress, balances, unlocked weapons, upgrade levels, owned skins and equipped items.</li><li><strong>Supply records:</strong> order identifiers, selected packs, displayed amounts and currencies, fulfilment status and virtual items granted.</li><li><strong>Session and technical information:</strong> session identifiers and information such as IP addresses, browser details and error records that may be processed by the application or its hosting systems.</li><li><strong>Correspondence:</strong> information you choose to include when contacting the operator.</li></ul><p>The current demonstration checkout does not ask for or process card numbers. Do not send payment-card details, passwords or sensitive personal information in a support request.</p></> },
        { id: 'purposes', title: 'Why information is used', content: <><p>Profile and game information is used to provide access, save progression, apply upgrades and deliver virtual items. Session information supports continuity and protects requests. Technical records help diagnose faults, prevent abuse and maintain the Service.</p><p>Where data protection law requires a lawful basis, the relevant purposes are providing the service you request, legitimate interests in operating and protecting it, compliance with legal obligations, or consent where required. A consent-based use must explain the purpose and how to withdraw consent before it begins.</p></> },
        { id: 'services', title: 'Service providers & external resources', content: <><p>Hosting and technical service providers may process information to operate the Service. The website currently loads fonts from Bunny Fonts. Requests for those resources disclose network information, including your IP address, to the provider.</p><p>No advertising or analytics integration is included in the current application. This does not mean that hosting infrastructure produces no technical logs. A real-money payment provider is not connected to the current demonstration checkout.</p><p>If providers, processing purposes or international data transfers change, this notice should be updated with the relevant recipients and safeguards before the new processing starts. Information may also need to be disclosed where required by law.</p></> },
        { id: 'retention', title: 'Storage, retention & security', content: <><p>Different information has different retention needs. Game records are kept to provide profile continuity; support and technical records are needed to resolve issues and protect the Service; legally required records may need to be retained for longer.</p><p>Retention should be limited to those purposes and applicable obligations. The current game does not offer an automatic account-deletion tool or a published fixed deletion schedule. Contact the operator to ask about the records associated with your access and their retention.</p><p>Access controls and request protections help safeguard information, but no internet service can guarantee absolute security. Keep your device and session secure and report suspected unauthorised access promptly.</p></> },
        { id: 'rights', title: 'Your choices & rights', content: <><p>Depending on the law that applies, you may be able to request access, correction, erasure, restriction or portability of your information, and object to certain processing. Where processing relies on consent, you may withdraw it without affecting earlier lawful processing.</p><p>Use the contact details below to make a request. Include enough information to identify the relevant profile, but not your password. Identity checks may be necessary to protect information from unauthorised disclosure. Requests remain subject to applicable exceptions and response periods.</p><p>You may also have a right to complain to your local data protection authority. Browser controls can manage local cookies; see the <Link href={navigation.cookies}>Cookie Policy</Link> for the consequences of clearing them.</p></> },
        { id: 'privacy-updates', title: 'Updates to this notice', content: <><p>The revision date above shows when this notice was last updated. Material changes to the way information is handled should be explained through an appropriate notice. Check this page when new account, shop or communication features become available.</p></> },
    ];
    return <LegalLayout type="privacy" title="Privacy Policy" introduction="Your progress belongs in the game. Understanding what happens to your information shouldn’t be another challenge." company={company} authenticated={is_authenticated} sections={sections} summary={['Profile and game data keep your progress connected.', 'The demo checkout does not collect card details.', 'External font requests reach the font provider.', 'You can contact the operator about your information.']} />;
}
