import React from 'react';
import { Link, usePage } from '@inertiajs/react';
import LegalLayout from '../../Layouts/LegalLayout';

export default function Terms({ company, is_authenticated }) {
    const { navigation } = usePage().props;
    const operator = company?.name || 'the operator identified in the company details below';
    const sections = [
        { id: 'agreement', title: 'Your agreement with us', content: <><p>These terms describe your use of Zombie Base Defender, its website and related game features (the “Service”), operated by {operator}. Read them together with our <Link href={navigation.privacy}>Privacy Policy</Link> and <Link href={navigation.cookies}>Cookie Policy</Link>.</p><p>Use the Service only if you can lawfully agree to these terms. If you require a parent or guardian’s permission under applicable law, obtain that permission before playing or making a purchase. If you do not agree, do not use the Service.</p></> },
        { id: 'access', title: 'Access & your progress', content: <><p>You may use the game for your personal entertainment. Keep access to your browser session and any account credentials secure. Do not impersonate another player or access a profile without permission.</p><p>Game progress is associated with the profile used by the Service. Guest or demonstration access is not a promise of a private, permanent or recoverable account. Clearing browser data or losing access to a session can interrupt access to your progress.</p></> },
        { id: 'fair-play', title: 'Fair play', content: <><p>Play fairly and respect the Service and other people. In particular, do not:</p><ul><li>Exploit vulnerabilities, manipulate balances or bypass purchase and progression checks.</li><li>Use automation to abuse gameplay, overload the Service or interfere with its operation.</li><li>Attempt unauthorised access to accounts, systems or information.</li><li>Upload or distribute unlawful, harmful or infringing material through the Service.</li></ul><p>Access may be restricted when reasonably necessary to investigate abuse, protect the Service or comply with law. Mandatory rights and legally required notice or review procedures remain unaffected.</p></> },
        { id: 'virtual-items', title: 'Gold, crystals & virtual items', content: <><p>Gold is used for weapon and barricade upgrades. Crystals unlock cosmetic finishes. Available packs, quantities and any applicable prices are shown in the shop before an order is submitted.</p><p>Virtual currency and items are game features, not money or investments. They cannot be exchanged for cash or transferred outside the features expressly provided by the Service. Cosmetic finishes do not by themselves increase weapon damage.</p><div className="legal-callout"><strong>Current checkout: demonstration mode</strong><p>This build fulfils supply orders as a simulation. It does not collect card details or charge a real payment method. Displayed prices are illustrative; a simulated order is not a real-money purchase.</p></div><p>If paid checkout is introduced, its price, payment provider, delivery conditions and cancellation information must be presented before payment. Nothing in these terms removes refund, withdrawal or other consumer rights that apply by law.</p></> },
        { id: 'content', title: 'Game content & ownership', content: <><p>The game’s code, branding, artwork and other content are protected by applicable intellectual property rights. Access gives you permission to use the Service, not ownership of its underlying content.</p><p>Do not redistribute or commercially exploit content without permission from the relevant rights holder. Third-party materials remain subject to their own licences. Nothing here restricts uses permitted by applicable law.</p></> },
        { id: 'availability', title: 'Updates & availability', content: <><p>The Service may change as the game develops. Maintenance, technical failures and updates can affect availability, game balance and compatibility. We do not promise uninterrupted access or that every feature will remain unchanged.</p><p>We will take reasonable care in providing the Service. To the extent permitted by law, it is otherwise provided as available. Nothing excludes liability that cannot legally be excluded, including mandatory consumer protections.</p></> },
        { id: 'changes', title: 'Changes & resolving questions', content: <><p>The date at the top of this document identifies its most recent revision. Material changes should be brought to players’ attention before they apply where required by law. New terms do not retrospectively remove rights already acquired.</p><p>If something goes wrong, contact the operator with a clear description of the issue and any relevant order reference. Do not include passwords or payment-card details. Applicable mandatory law and any rights to bring a claim before a competent court remain unaffected.</p></> },
    ];
    return <LegalLayout type="terms" title="Terms of Service" introduction="The rules that keep the outpost running. Your access, your virtual items and what you can expect from us — in plain language." company={company} authenticated={is_authenticated} sections={sections} summary={['Play fairly and keep your access secure.', 'Gold, crystals and skins are virtual game items.', 'The current checkout is a demonstration, not a real charge.', 'Your mandatory consumer rights remain protected.']} />;
}
